<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBookAir.fios-router.home" failures="4" tests="34" name="apiRunner.TestRunner" time="6.821" errors="0" timestamp="2024-11-22T12:27:22 EST" skipped="0">
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.222"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.158"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.220"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.208"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.133"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.162"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.207">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at generics.ApiUtils.validateStatusCode(ApiUtils.java:27)
at stepDefinitions.class2Steps.admin_receives_status_for_updateClass(class2Steps.java:397)
at ✽.Admin receives 400 "Bad Request" Status for updateClass(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/Team2_ChangeMakers_RestAssured/src/test/resources/features/class2.feature:172)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.179"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.194">
    <failure message="expected [404] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at generics.ApiUtils.validateStatusCode(ApiUtils.java:27)
at stepDefinitions.class2Steps.admin_receives_status_for_getUpcomingClasses(class2Steps.java:314)
at ✽.Admin receives 404 "Not Found" Status for getUpcomingClasses(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/Team2_ChangeMakers_RestAssured/src/test/resources/features/class2.feature:116)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.272">
    <failure message="expected [404] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at generics.ApiUtils.validateStatusCode(ApiUtils.java:27)
at stepDefinitions.class2Steps.admin_receives_status_for_updateClass(class2Steps.java:397)
at ✽.Admin receives 404 "Not Found" Status for updateClass(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/Team2_ChangeMakers_RestAssured/src/test/resources/features/class2.feature:177)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.153"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.238"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.277"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.207"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.546"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.173"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.163"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.218"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.142"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.196"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.163"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.197"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.178"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.192">
    <failure message="expected [401] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [401] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at generics.ApiUtils.validateStatusCode(ApiUtils.java:27)
at stepDefinitions.class2Steps.admin_receives_status_for_updateClass(class2Steps.java:397)
at ✽.Admin receives 401 "Unauthorized" Status for updateClass(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/Team2_ChangeMakers_RestAssured/src/test/resources/features/class2.feature:147)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.243"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.155"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.136"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.104"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.265"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.185"/>
  <testcase classname="apiRunner.TestRunner" name="runScenario" time="0.190"/>
</testsuite> <!-- apiRunner.TestRunner -->
